// Code generated by protoc-gen-go. DO NOT EDIT.
// source: header.proto

package gotp

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// AccessServer可识别header，用于外部请求
type AccessRequestHeader struct {
	//设备id
	ClientId string `protobuf:"bytes,1,opt,name=clientId,proto3" json:"clientId,omitempty"`
	//来源
	ClientType ClientType `protobuf:"varint,2,opt,name=clientType,proto3,enum=gotp.ClientType" json:"clientType,omitempty"`
	//版本号x.y.z，与请求url中的版本不同，此版本为业务协议版本
	Version string `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	//token
	Token                string   `protobuf:"bytes,4,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AccessRequestHeader) Reset()         { *m = AccessRequestHeader{} }
func (m *AccessRequestHeader) String() string { return proto.CompactTextString(m) }
func (*AccessRequestHeader) ProtoMessage()    {}
func (*AccessRequestHeader) Descriptor() ([]byte, []int) {
	return fileDescriptor_6398613e36d6c2ce, []int{0}
}

func (m *AccessRequestHeader) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AccessRequestHeader.Unmarshal(m, b)
}
func (m *AccessRequestHeader) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AccessRequestHeader.Marshal(b, m, deterministic)
}
func (m *AccessRequestHeader) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccessRequestHeader.Merge(m, src)
}
func (m *AccessRequestHeader) XXX_Size() int {
	return xxx_messageInfo_AccessRequestHeader.Size(m)
}
func (m *AccessRequestHeader) XXX_DiscardUnknown() {
	xxx_messageInfo_AccessRequestHeader.DiscardUnknown(m)
}

var xxx_messageInfo_AccessRequestHeader proto.InternalMessageInfo

func (m *AccessRequestHeader) GetClientId() string {
	if m != nil {
		return m.ClientId
	}
	return ""
}

func (m *AccessRequestHeader) GetClientType() ClientType {
	if m != nil {
		return m.ClientType
	}
	return ClientType_Reserve
}

func (m *AccessRequestHeader) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *AccessRequestHeader) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type AccessResponseHeader struct {
	//业务返回码
	Retcode int32 `protobuf:"varint,1,opt,name=retcode,proto3" json:"retcode,omitempty"`
	//业务返回消息
	Retmsg string `protobuf:"bytes,2,opt,name=retmsg,proto3" json:"retmsg,omitempty"`
	//请求id
	RequestId            string   `protobuf:"bytes,3,opt,name=requestId,proto3" json:"requestId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AccessResponseHeader) Reset()         { *m = AccessResponseHeader{} }
func (m *AccessResponseHeader) String() string { return proto.CompactTextString(m) }
func (*AccessResponseHeader) ProtoMessage()    {}
func (*AccessResponseHeader) Descriptor() ([]byte, []int) {
	return fileDescriptor_6398613e36d6c2ce, []int{1}
}

func (m *AccessResponseHeader) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AccessResponseHeader.Unmarshal(m, b)
}
func (m *AccessResponseHeader) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AccessResponseHeader.Marshal(b, m, deterministic)
}
func (m *AccessResponseHeader) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccessResponseHeader.Merge(m, src)
}
func (m *AccessResponseHeader) XXX_Size() int {
	return xxx_messageInfo_AccessResponseHeader.Size(m)
}
func (m *AccessResponseHeader) XXX_DiscardUnknown() {
	xxx_messageInfo_AccessResponseHeader.DiscardUnknown(m)
}

var xxx_messageInfo_AccessResponseHeader proto.InternalMessageInfo

func (m *AccessResponseHeader) GetRetcode() int32 {
	if m != nil {
		return m.Retcode
	}
	return 0
}

func (m *AccessResponseHeader) GetRetmsg() string {
	if m != nil {
		return m.Retmsg
	}
	return ""
}

func (m *AccessResponseHeader) GetRequestId() string {
	if m != nil {
		return m.RequestId
	}
	return ""
}

// 用于内部RPC请求
type RequestHeader struct {
	//请求id
	RequestId string `protobuf:"bytes,1,opt,name=requestId,proto3" json:"requestId,omitempty"`
	//设备id
	ClientId string `protobuf:"bytes,2,opt,name=clientId,proto3" json:"clientId,omitempty"`
	//来源
	ClientType ClientType `protobuf:"varint,3,opt,name=clientType,proto3,enum=gotp.ClientType" json:"clientType,omitempty"`
	//版本号x.y.z，与请求url中的版本不同，此版本为业务协议版本
	Version string `protobuf:"bytes,4,opt,name=version,proto3" json:"version,omitempty"`
	//测试标志位
	TestFlag             bool     `protobuf:"varint,5,opt,name=testFlag,proto3" json:"testFlag,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RequestHeader) Reset()         { *m = RequestHeader{} }
func (m *RequestHeader) String() string { return proto.CompactTextString(m) }
func (*RequestHeader) ProtoMessage()    {}
func (*RequestHeader) Descriptor() ([]byte, []int) {
	return fileDescriptor_6398613e36d6c2ce, []int{2}
}

func (m *RequestHeader) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestHeader.Unmarshal(m, b)
}
func (m *RequestHeader) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestHeader.Marshal(b, m, deterministic)
}
func (m *RequestHeader) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestHeader.Merge(m, src)
}
func (m *RequestHeader) XXX_Size() int {
	return xxx_messageInfo_RequestHeader.Size(m)
}
func (m *RequestHeader) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestHeader.DiscardUnknown(m)
}

var xxx_messageInfo_RequestHeader proto.InternalMessageInfo

func (m *RequestHeader) GetRequestId() string {
	if m != nil {
		return m.RequestId
	}
	return ""
}

func (m *RequestHeader) GetClientId() string {
	if m != nil {
		return m.ClientId
	}
	return ""
}

func (m *RequestHeader) GetClientType() ClientType {
	if m != nil {
		return m.ClientType
	}
	return ClientType_Reserve
}

func (m *RequestHeader) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *RequestHeader) GetTestFlag() bool {
	if m != nil {
		return m.TestFlag
	}
	return false
}

type ResponseHeader struct {
	//业务返回码
	Retcode RetcodeType `protobuf:"varint,1,opt,name=retcode,proto3,enum=gotp.RetcodeType" json:"retcode,omitempty"`
	//业务返回消息
	Retmsg string `protobuf:"bytes,2,opt,name=retmsg,proto3" json:"retmsg,omitempty"`
	//请求id
	RequestId            string   `protobuf:"bytes,3,opt,name=requestId,proto3" json:"requestId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResponseHeader) Reset()         { *m = ResponseHeader{} }
func (m *ResponseHeader) String() string { return proto.CompactTextString(m) }
func (*ResponseHeader) ProtoMessage()    {}
func (*ResponseHeader) Descriptor() ([]byte, []int) {
	return fileDescriptor_6398613e36d6c2ce, []int{3}
}

func (m *ResponseHeader) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResponseHeader.Unmarshal(m, b)
}
func (m *ResponseHeader) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResponseHeader.Marshal(b, m, deterministic)
}
func (m *ResponseHeader) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResponseHeader.Merge(m, src)
}
func (m *ResponseHeader) XXX_Size() int {
	return xxx_messageInfo_ResponseHeader.Size(m)
}
func (m *ResponseHeader) XXX_DiscardUnknown() {
	xxx_messageInfo_ResponseHeader.DiscardUnknown(m)
}

var xxx_messageInfo_ResponseHeader proto.InternalMessageInfo

func (m *ResponseHeader) GetRetcode() RetcodeType {
	if m != nil {
		return m.Retcode
	}
	return RetcodeType_RetSuccess
}

func (m *ResponseHeader) GetRetmsg() string {
	if m != nil {
		return m.Retmsg
	}
	return ""
}

func (m *ResponseHeader) GetRequestId() string {
	if m != nil {
		return m.RequestId
	}
	return ""
}

func init() {
	proto.RegisterType((*AccessRequestHeader)(nil), "gotp.AccessRequestHeader")
	proto.RegisterType((*AccessResponseHeader)(nil), "gotp.AccessResponseHeader")
	proto.RegisterType((*RequestHeader)(nil), "gotp.RequestHeader")
	proto.RegisterType((*ResponseHeader)(nil), "gotp.ResponseHeader")
}

func init() { proto.RegisterFile("header.proto", fileDescriptor_6398613e36d6c2ce) }

var fileDescriptor_6398613e36d6c2ce = []byte{
	// 281 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x92, 0xd1, 0x4a, 0xc3, 0x30,
	0x14, 0x86, 0xc9, 0xd6, 0x6e, 0xed, 0x61, 0x16, 0x8d, 0x43, 0x42, 0xf1, 0xa2, 0xf4, 0xaa, 0x20,
	0x14, 0x99, 0x4f, 0x20, 0x82, 0xb8, 0xdb, 0xe0, 0x0b, 0xcc, 0xf6, 0x58, 0x87, 0x6b, 0x52, 0x93,
	0x28, 0xf8, 0x1c, 0x3e, 0x89, 0x6f, 0x28, 0x26, 0x6d, 0x35, 0xbb, 0x10, 0x64, 0x77, 0xfd, 0x7f,
	0x4e, 0xcf, 0xff, 0x9f, 0x8f, 0xc0, 0xe2, 0x09, 0x37, 0x35, 0xaa, 0xb2, 0x53, 0xd2, 0x48, 0x1a,
	0x34, 0xd2, 0x74, 0xe9, 0xa2, 0x92, 0x6d, 0x2b, 0x85, 0xf3, 0xf2, 0x0f, 0x02, 0xa7, 0xd7, 0x55,
	0x85, 0x5a, 0x73, 0x7c, 0x79, 0x45, 0x6d, 0xee, 0xec, 0x1f, 0x34, 0x85, 0xa8, 0xda, 0x6d, 0x51,
	0x98, 0x75, 0xcd, 0x48, 0x46, 0x8a, 0x98, 0x8f, 0x9a, 0x5e, 0x02, 0xb8, 0xef, 0xfb, 0xf7, 0x0e,
	0xd9, 0x24, 0x23, 0x45, 0xb2, 0x3a, 0x2e, 0xbf, 0x97, 0x97, 0x37, 0xa3, 0xcf, 0x7f, 0xcd, 0x50,
	0x06, 0xf3, 0x37, 0x54, 0x7a, 0x2b, 0x05, 0x9b, 0xda, 0x65, 0x83, 0xa4, 0x4b, 0x08, 0x8d, 0x7c,
	0x46, 0xc1, 0x02, 0xeb, 0x3b, 0x91, 0x3f, 0xc2, 0x72, 0x28, 0xa5, 0x3b, 0x29, 0x34, 0xf6, 0xad,
	0x18, 0xcc, 0x15, 0x9a, 0x4a, 0xd6, 0x68, 0x4b, 0x85, 0x7c, 0x90, 0xf4, 0x0c, 0x66, 0x0a, 0x4d,
	0xab, 0x1b, 0xdb, 0x27, 0xe6, 0xbd, 0xa2, 0xe7, 0x10, 0x2b, 0x77, 0xd8, 0xba, 0xee, 0xb3, 0x7f,
	0x8c, 0xfc, 0x93, 0xc0, 0x91, 0x7f, 0xb7, 0x37, 0x4f, 0xf6, 0xe6, 0x3d, 0x2a, 0x93, 0x3f, 0xa9,
	0x4c, 0xff, 0x47, 0x25, 0xf0, 0xa9, 0xa4, 0x10, 0x19, 0xd4, 0xe6, 0x76, 0xb7, 0x69, 0x58, 0x98,
	0x91, 0x22, 0xe2, 0xa3, 0xce, 0x35, 0x24, 0x7b, 0x54, 0x2e, 0x7c, 0x2a, 0xc9, 0xea, 0xc4, 0xc5,
	0x72, 0x67, 0xda, 0xdc, 0xc3, 0x40, 0x3d, 0xcc, 0xec, 0x6b, 0xb9, 0xfa, 0x0a, 0x00, 0x00, 0xff,
	0xff, 0xe0, 0x30, 0x82, 0x28, 0x51, 0x02, 0x00, 0x00,
}
