// Code generated by protoc-gen-go. DO NOT EDIT.
// source: template_server/template_service.proto

package gotp_TemplateServer

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	proto1 "github.com/gotp/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// !!!!!!!!!!!!!!!!!!!!!!!!!!!!! WARNING !!!!!!!!!!!!!!!!!!!!!!!!!!!!!
// Please not remove or modify comment below, it's anchor for new code
// ############################# REQUEST #############################
type TestRequest struct {
	RequestId            string            `protobuf:"bytes,1,opt,name=requestId,proto3" json:"requestId,omitempty"`
	ClientId             string            `protobuf:"bytes,2,opt,name=clientId,proto3" json:"clientId,omitempty"`
	ClientType           proto1.ClientType `protobuf:"varint,3,opt,name=clientType,proto3,enum=gotp.ClientType" json:"clientType,omitempty"`
	Version              string            `protobuf:"bytes,4,opt,name=version,proto3" json:"version,omitempty"`
	TestFlag             bool              `protobuf:"varint,5,opt,name=testFlag,proto3" json:"testFlag,omitempty"`
	Data                 *TestRequestData  `protobuf:"bytes,6,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *TestRequest) Reset()         { *m = TestRequest{} }
func (m *TestRequest) String() string { return proto.CompactTextString(m) }
func (*TestRequest) ProtoMessage()    {}
func (*TestRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_82a19b8302408222, []int{0}
}

func (m *TestRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TestRequest.Unmarshal(m, b)
}
func (m *TestRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TestRequest.Marshal(b, m, deterministic)
}
func (m *TestRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TestRequest.Merge(m, src)
}
func (m *TestRequest) XXX_Size() int {
	return xxx_messageInfo_TestRequest.Size(m)
}
func (m *TestRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TestRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TestRequest proto.InternalMessageInfo

func (m *TestRequest) GetRequestId() string {
	if m != nil {
		return m.RequestId
	}
	return ""
}

func (m *TestRequest) GetClientId() string {
	if m != nil {
		return m.ClientId
	}
	return ""
}

func (m *TestRequest) GetClientType() proto1.ClientType {
	if m != nil {
		return m.ClientType
	}
	return proto1.ClientType_Reserve
}

func (m *TestRequest) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *TestRequest) GetTestFlag() bool {
	if m != nil {
		return m.TestFlag
	}
	return false
}

func (m *TestRequest) GetData() *TestRequestData {
	if m != nil {
		return m.Data
	}
	return nil
}

type TestResponse struct {
	Retcode              proto1.RetcodeType `protobuf:"varint,1,opt,name=retcode,proto3,enum=gotp.RetcodeType" json:"retcode,omitempty"`
	Retmsg               string             `protobuf:"bytes,2,opt,name=retmsg,proto3" json:"retmsg,omitempty"`
	RequestId            string             `protobuf:"bytes,3,opt,name=requestId,proto3" json:"requestId,omitempty"`
	Data                 *TestResponseData  `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *TestResponse) Reset()         { *m = TestResponse{} }
func (m *TestResponse) String() string { return proto.CompactTextString(m) }
func (*TestResponse) ProtoMessage()    {}
func (*TestResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_82a19b8302408222, []int{1}
}

func (m *TestResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TestResponse.Unmarshal(m, b)
}
func (m *TestResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TestResponse.Marshal(b, m, deterministic)
}
func (m *TestResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TestResponse.Merge(m, src)
}
func (m *TestResponse) XXX_Size() int {
	return xxx_messageInfo_TestResponse.Size(m)
}
func (m *TestResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_TestResponse.DiscardUnknown(m)
}

var xxx_messageInfo_TestResponse proto.InternalMessageInfo

func (m *TestResponse) GetRetcode() proto1.RetcodeType {
	if m != nil {
		return m.Retcode
	}
	return proto1.RetcodeType_RetSuccess
}

func (m *TestResponse) GetRetmsg() string {
	if m != nil {
		return m.Retmsg
	}
	return ""
}

func (m *TestResponse) GetRequestId() string {
	if m != nil {
		return m.RequestId
	}
	return ""
}

func (m *TestResponse) GetData() *TestResponseData {
	if m != nil {
		return m.Data
	}
	return nil
}

type TestRequestData struct {
	// Define data field here
	Dummy                int32    `protobuf:"varint,1,opt,name=dummy,proto3" json:"dummy,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TestRequestData) Reset()         { *m = TestRequestData{} }
func (m *TestRequestData) String() string { return proto.CompactTextString(m) }
func (*TestRequestData) ProtoMessage()    {}
func (*TestRequestData) Descriptor() ([]byte, []int) {
	return fileDescriptor_82a19b8302408222, []int{2}
}

func (m *TestRequestData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TestRequestData.Unmarshal(m, b)
}
func (m *TestRequestData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TestRequestData.Marshal(b, m, deterministic)
}
func (m *TestRequestData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TestRequestData.Merge(m, src)
}
func (m *TestRequestData) XXX_Size() int {
	return xxx_messageInfo_TestRequestData.Size(m)
}
func (m *TestRequestData) XXX_DiscardUnknown() {
	xxx_messageInfo_TestRequestData.DiscardUnknown(m)
}

var xxx_messageInfo_TestRequestData proto.InternalMessageInfo

func (m *TestRequestData) GetDummy() int32 {
	if m != nil {
		return m.Dummy
	}
	return 0
}

type TestResponseData struct {
	// Define data field here
	Dummy                int32    `protobuf:"varint,1,opt,name=dummy,proto3" json:"dummy,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TestResponseData) Reset()         { *m = TestResponseData{} }
func (m *TestResponseData) String() string { return proto.CompactTextString(m) }
func (*TestResponseData) ProtoMessage()    {}
func (*TestResponseData) Descriptor() ([]byte, []int) {
	return fileDescriptor_82a19b8302408222, []int{3}
}

func (m *TestResponseData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TestResponseData.Unmarshal(m, b)
}
func (m *TestResponseData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TestResponseData.Marshal(b, m, deterministic)
}
func (m *TestResponseData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TestResponseData.Merge(m, src)
}
func (m *TestResponseData) XXX_Size() int {
	return xxx_messageInfo_TestResponseData.Size(m)
}
func (m *TestResponseData) XXX_DiscardUnknown() {
	xxx_messageInfo_TestResponseData.DiscardUnknown(m)
}

var xxx_messageInfo_TestResponseData proto.InternalMessageInfo

func (m *TestResponseData) GetDummy() int32 {
	if m != nil {
		return m.Dummy
	}
	return 0
}

func init() {
	proto.RegisterType((*TestRequest)(nil), "gotp.TemplateServer.TestRequest")
	proto.RegisterType((*TestResponse)(nil), "gotp.TemplateServer.TestResponse")
	proto.RegisterType((*TestRequestData)(nil), "gotp.TemplateServer.TestRequestData")
	proto.RegisterType((*TestResponseData)(nil), "gotp.TemplateServer.TestResponseData")
}

func init() {
	proto.RegisterFile("template_server/template_service.proto", fileDescriptor_82a19b8302408222)
}

var fileDescriptor_82a19b8302408222 = []byte{
	// 355 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x52, 0x4d, 0x4f, 0x83, 0x40,
	0x14, 0x14, 0x4b, 0xbf, 0x5e, 0x4d, 0xad, 0xab, 0x31, 0x84, 0x78, 0x40, 0xfc, 0x22, 0x31, 0x01,
	0x83, 0x17, 0x3d, 0x6b, 0x4c, 0x3c, 0x78, 0xc1, 0xde, 0x95, 0xc2, 0x0b, 0x92, 0x74, 0x59, 0xdc,
	0xdd, 0x36, 0xe9, 0x7f, 0xf2, 0x8f, 0xf9, 0x2f, 0x0c, 0xbb, 0xf4, 0x33, 0x8d, 0xbd, 0x31, 0x6f,
	0xe6, 0xcd, 0xce, 0x9b, 0x00, 0xd7, 0x12, 0x69, 0x39, 0x8e, 0x25, 0x7e, 0x08, 0xe4, 0x53, 0xe4,
	0xc1, 0x1a, 0xce, 0x13, 0xf4, 0x4b, 0xce, 0x24, 0x23, 0xc7, 0x19, 0x93, 0xa5, 0x3f, 0xac, 0xc9,
	0x77, 0xa5, 0xb5, 0xdd, 0x2c, 0x97, 0x5f, 0x93, 0x91, 0x9f, 0x30, 0x1a, 0x54, 0x7c, 0xa0, 0xb4,
	0x41, 0xc2, 0x28, 0x65, 0x85, 0x5e, 0xb4, 0x2f, 0xb6, 0x6b, 0x38, 0xca, 0x84, 0xa5, 0xb5, 0xbb,
	0xfb, 0x6b, 0x40, 0x6f, 0x88, 0x42, 0x46, 0xf8, 0x3d, 0x41, 0x21, 0xc9, 0x19, 0x74, 0xb9, 0xfe,
	0x7c, 0x4d, 0x2d, 0xc3, 0x31, 0xbc, 0x6e, 0xb4, 0x1c, 0x10, 0x1b, 0x3a, 0xc9, 0x38, 0xc7, 0xa2,
	0x22, 0xf7, 0x15, 0xb9, 0xc0, 0xe4, 0x0e, 0x40, 0x7f, 0x0f, 0x67, 0x25, 0x5a, 0x0d, 0xc7, 0xf0,
	0xfa, 0xe1, 0xc0, 0x57, 0xe1, 0x9f, 0x16, 0xf3, 0x68, 0x45, 0x43, 0x2c, 0x68, 0x4f, 0x91, 0x8b,
	0x9c, 0x15, 0x96, 0xa9, 0xcc, 0xe6, 0xb0, 0x7a, 0x47, 0xa2, 0x90, 0x2f, 0xe3, 0x38, 0xb3, 0x9a,
	0x8e, 0xe1, 0x75, 0xa2, 0x05, 0x26, 0x0f, 0x60, 0xa6, 0xb1, 0x8c, 0xad, 0x96, 0x63, 0x78, 0xbd,
	0xf0, 0xd2, 0xdf, 0x52, 0x8f, 0xbf, 0x72, 0xd1, 0x73, 0x2c, 0xe3, 0x48, 0x6d, 0xb8, 0x3f, 0x06,
	0x1c, 0x68, 0x46, 0x94, 0xac, 0x10, 0x48, 0x6e, 0xa1, 0x5d, 0xb7, 0xa1, 0x4e, 0xed, 0x87, 0x47,
	0xda, 0x2d, 0xd2, 0x43, 0x15, 0x78, 0xae, 0x20, 0xa7, 0xd0, 0xe2, 0x28, 0xa9, 0xc8, 0xea, 0xcb,
	0x6b, 0xb4, 0xde, 0x58, 0x63, 0xb3, 0xb1, 0xc7, 0x3a, 0xad, 0xa9, 0xd2, 0x5e, 0xfd, 0x93, 0x56,
	0x67, 0x5a, 0x89, 0x7b, 0x03, 0x87, 0x1b, 0x77, 0x90, 0x13, 0x68, 0xa6, 0x13, 0x4a, 0x67, 0x2a,
	0x6e, 0x33, 0xd2, 0xc0, 0xf5, 0x60, 0xb0, 0x69, 0xb1, 0x5d, 0x19, 0x7e, 0x56, 0x96, 0xcb, 0xb7,
	0xf3, 0x04, 0xc9, 0x1b, 0x98, 0xd5, 0x32, 0x71, 0x76, 0x15, 0x69, 0x9f, 0xef, 0x0c, 0xef, 0xee,
	0x8d, 0x5a, 0xea, 0xb7, 0xba, 0xff, 0x0b, 0x00, 0x00, 0xff, 0xff, 0x44, 0x25, 0x6c, 0x48, 0xde,
	0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// TemplateServiceClient is the client API for TemplateService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type TemplateServiceClient interface {
	// !!!!!!!!!!!!!!!!!!!!!!!!!!!!! WARNING !!!!!!!!!!!!!!!!!!!!!!!!!!!!!
	// Please not remove or modify comment below, it's anchor for new code
	// ########################### INTERFACE #############################
	Test(ctx context.Context, in *TestRequest, opts ...grpc.CallOption) (*TestResponse, error)
}

type templateServiceClient struct {
	cc *grpc.ClientConn
}

func NewTemplateServiceClient(cc *grpc.ClientConn) TemplateServiceClient {
	return &templateServiceClient{cc}
}

func (c *templateServiceClient) Test(ctx context.Context, in *TestRequest, opts ...grpc.CallOption) (*TestResponse, error) {
	out := new(TestResponse)
	err := c.cc.Invoke(ctx, "/gotp.TemplateServer.TemplateService/Test", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TemplateServiceServer is the server API for TemplateService service.
type TemplateServiceServer interface {
	// !!!!!!!!!!!!!!!!!!!!!!!!!!!!! WARNING !!!!!!!!!!!!!!!!!!!!!!!!!!!!!
	// Please not remove or modify comment below, it's anchor for new code
	// ########################### INTERFACE #############################
	Test(context.Context, *TestRequest) (*TestResponse, error)
}

// UnimplementedTemplateServiceServer can be embedded to have forward compatible implementations.
type UnimplementedTemplateServiceServer struct {
}

func (*UnimplementedTemplateServiceServer) Test(ctx context.Context, req *TestRequest) (*TestResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Test not implemented")
}

func RegisterTemplateServiceServer(s *grpc.Server, srv TemplateServiceServer) {
	s.RegisterService(&_TemplateService_serviceDesc, srv)
}

func _TemplateService_Test_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TemplateServiceServer).Test(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gotp.TemplateServer.TemplateService/Test",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TemplateServiceServer).Test(ctx, req.(*TestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _TemplateService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "gotp.TemplateServer.TemplateService",
	HandlerType: (*TemplateServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Test",
			Handler:    _TemplateService_Test_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "template_server/template_service.proto",
}
