// Code generated by protoc-gen-go. DO NOT EDIT.
// source: template_service.proto

package gotp_TemplateServer

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	proto1 "github.com/gotp/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// ############ REQUEST ############
type TestRequest struct {
	Header               *proto1.RequestHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Data                 *TestRequestData      `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *TestRequest) Reset()         { *m = TestRequest{} }
func (m *TestRequest) String() string { return proto.CompactTextString(m) }
func (*TestRequest) ProtoMessage()    {}
func (*TestRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9728ed5f14c58c71, []int{0}
}

func (m *TestRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TestRequest.Unmarshal(m, b)
}
func (m *TestRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TestRequest.Marshal(b, m, deterministic)
}
func (m *TestRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TestRequest.Merge(m, src)
}
func (m *TestRequest) XXX_Size() int {
	return xxx_messageInfo_TestRequest.Size(m)
}
func (m *TestRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TestRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TestRequest proto.InternalMessageInfo

func (m *TestRequest) GetHeader() *proto1.RequestHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *TestRequest) GetData() *TestRequestData {
	if m != nil {
		return m.Data
	}
	return nil
}

type TestResponse struct {
	Header               *proto1.ResponseHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Data                 *TestResponseData      `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *TestResponse) Reset()         { *m = TestResponse{} }
func (m *TestResponse) String() string { return proto.CompactTextString(m) }
func (*TestResponse) ProtoMessage()    {}
func (*TestResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9728ed5f14c58c71, []int{1}
}

func (m *TestResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TestResponse.Unmarshal(m, b)
}
func (m *TestResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TestResponse.Marshal(b, m, deterministic)
}
func (m *TestResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TestResponse.Merge(m, src)
}
func (m *TestResponse) XXX_Size() int {
	return xxx_messageInfo_TestResponse.Size(m)
}
func (m *TestResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_TestResponse.DiscardUnknown(m)
}

var xxx_messageInfo_TestResponse proto.InternalMessageInfo

func (m *TestResponse) GetHeader() *proto1.ResponseHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *TestResponse) GetData() *TestResponseData {
	if m != nil {
		return m.Data
	}
	return nil
}

type TestRequestData struct {
	// Define data field here
	Dummy                int32    `protobuf:"varint,1,opt,name=dummy,proto3" json:"dummy,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TestRequestData) Reset()         { *m = TestRequestData{} }
func (m *TestRequestData) String() string { return proto.CompactTextString(m) }
func (*TestRequestData) ProtoMessage()    {}
func (*TestRequestData) Descriptor() ([]byte, []int) {
	return fileDescriptor_9728ed5f14c58c71, []int{2}
}

func (m *TestRequestData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TestRequestData.Unmarshal(m, b)
}
func (m *TestRequestData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TestRequestData.Marshal(b, m, deterministic)
}
func (m *TestRequestData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TestRequestData.Merge(m, src)
}
func (m *TestRequestData) XXX_Size() int {
	return xxx_messageInfo_TestRequestData.Size(m)
}
func (m *TestRequestData) XXX_DiscardUnknown() {
	xxx_messageInfo_TestRequestData.DiscardUnknown(m)
}

var xxx_messageInfo_TestRequestData proto.InternalMessageInfo

func (m *TestRequestData) GetDummy() int32 {
	if m != nil {
		return m.Dummy
	}
	return 0
}

type TestResponseData struct {
	// Define data field here
	Dummy                int32    `protobuf:"varint,1,opt,name=dummy,proto3" json:"dummy,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TestResponseData) Reset()         { *m = TestResponseData{} }
func (m *TestResponseData) String() string { return proto.CompactTextString(m) }
func (*TestResponseData) ProtoMessage()    {}
func (*TestResponseData) Descriptor() ([]byte, []int) {
	return fileDescriptor_9728ed5f14c58c71, []int{3}
}

func (m *TestResponseData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TestResponseData.Unmarshal(m, b)
}
func (m *TestResponseData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TestResponseData.Marshal(b, m, deterministic)
}
func (m *TestResponseData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TestResponseData.Merge(m, src)
}
func (m *TestResponseData) XXX_Size() int {
	return xxx_messageInfo_TestResponseData.Size(m)
}
func (m *TestResponseData) XXX_DiscardUnknown() {
	xxx_messageInfo_TestResponseData.DiscardUnknown(m)
}

var xxx_messageInfo_TestResponseData proto.InternalMessageInfo

func (m *TestResponseData) GetDummy() int32 {
	if m != nil {
		return m.Dummy
	}
	return 0
}

func init() {
	proto.RegisterType((*TestRequest)(nil), "gotp.TemplateServer.TestRequest")
	proto.RegisterType((*TestResponse)(nil), "gotp.TemplateServer.TestResponse")
	proto.RegisterType((*TestRequestData)(nil), "gotp.TemplateServer.TestRequestData")
	proto.RegisterType((*TestResponseData)(nil), "gotp.TemplateServer.TestResponseData")
}

func init() { proto.RegisterFile("template_service.proto", fileDescriptor_9728ed5f14c58c71) }

var fileDescriptor_9728ed5f14c58c71 = []byte{
	// 249 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x91, 0xc1, 0x4b, 0xc3, 0x30,
	0x14, 0xc6, 0x9d, 0x6c, 0x3b, 0xbc, 0x09, 0x4a, 0x36, 0x64, 0xec, 0x34, 0x83, 0xe2, 0x40, 0x49,
	0x61, 0x5e, 0xf4, 0xee, 0xc1, 0x8b, 0x97, 0xb8, 0xbb, 0x66, 0xed, 0x63, 0x2b, 0x18, 0x13, 0x93,
	0xd7, 0x89, 0xff, 0xbd, 0x34, 0xa9, 0x38, 0x43, 0x59, 0x8f, 0xe5, 0xf7, 0x7d, 0xdf, 0xef, 0xd1,
	0xc0, 0x39, 0xa1, 0xb6, 0xef, 0x8a, 0xf0, 0xd5, 0xa3, 0xdb, 0x95, 0x39, 0x0a, 0xeb, 0x0c, 0x19,
	0x36, 0xde, 0x18, 0xb2, 0x62, 0xd5, 0xc0, 0x17, 0x74, 0x3b, 0x74, 0x33, 0xbe, 0x29, 0x69, 0x5b,
	0xad, 0x45, 0x6e, 0x74, 0x56, 0xf3, 0x2c, 0x64, 0xb3, 0x2d, 0xaa, 0x02, 0x5d, 0x2c, 0x72, 0x82,
	0xd1, 0x0a, 0x3d, 0x49, 0xfc, 0xac, 0xd0, 0x13, 0xbb, 0x81, 0x61, 0xc4, 0xd3, 0xde, 0xbc, 0xb7,
	0x18, 0x2d, 0xc7, 0x22, 0x0c, 0x37, 0xf8, 0x29, 0x20, 0xd9, 0x44, 0xd8, 0x3d, 0xf4, 0x0b, 0x45,
	0x6a, 0x7a, 0x1c, 0xa2, 0x97, 0xa2, 0xe5, 0x06, 0xb1, 0x37, 0xfe, 0xa8, 0x48, 0xc9, 0xd0, 0xe0,
	0x5f, 0x70, 0x12, 0x81, 0xb7, 0xe6, 0xc3, 0x23, 0xbb, 0x4d, 0xb4, 0x93, 0x5f, 0x6d, 0xe4, 0x89,
	0xf7, 0xe1, 0x9f, 0xf7, 0xea, 0x80, 0x37, 0xd6, 0xf7, 0xc4, 0xd7, 0x70, 0x9a, 0x5c, 0xc4, 0x26,
	0x30, 0x28, 0x2a, 0xad, 0xbf, 0x83, 0x7a, 0x20, 0xe3, 0x07, 0x5f, 0xc0, 0x59, 0x3a, 0xd1, 0x9e,
	0x5c, 0xbe, 0xd5, 0x93, 0x7f, 0xee, 0x32, 0x47, 0xf6, 0x0c, 0xfd, 0xba, 0xcc, 0xe6, 0x5d, 0xbf,
	0x64, 0x76, 0xd1, 0x79, 0x3c, 0x3f, 0x5a, 0x0f, 0xc3, 0x53, 0xdd, 0xfd, 0x04, 0x00, 0x00, 0xff,
	0xff, 0xa1, 0x61, 0xb1, 0xb4, 0xfd, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// TemplateServiceClient is the client API for TemplateService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type TemplateServiceClient interface {
	// ############ INTERFACE ############
	Test(ctx context.Context, in *TestRequest, opts ...grpc.CallOption) (*TestResponse, error)
}

type templateServiceClient struct {
	cc *grpc.ClientConn
}

func NewTemplateServiceClient(cc *grpc.ClientConn) TemplateServiceClient {
	return &templateServiceClient{cc}
}

func (c *templateServiceClient) Test(ctx context.Context, in *TestRequest, opts ...grpc.CallOption) (*TestResponse, error) {
	out := new(TestResponse)
	err := c.cc.Invoke(ctx, "/gotp.TemplateServer.TemplateService/Test", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TemplateServiceServer is the server API for TemplateService service.
type TemplateServiceServer interface {
	// ############ INTERFACE ############
	Test(context.Context, *TestRequest) (*TestResponse, error)
}

// UnimplementedTemplateServiceServer can be embedded to have forward compatible implementations.
type UnimplementedTemplateServiceServer struct {
}

func (*UnimplementedTemplateServiceServer) Test(ctx context.Context, req *TestRequest) (*TestResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Test not implemented")
}

func RegisterTemplateServiceServer(s *grpc.Server, srv TemplateServiceServer) {
	s.RegisterService(&_TemplateService_serviceDesc, srv)
}

func _TemplateService_Test_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TemplateServiceServer).Test(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gotp.TemplateServer.TemplateService/Test",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TemplateServiceServer).Test(ctx, req.(*TestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _TemplateService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "gotp.TemplateServer.TemplateService",
	HandlerType: (*TemplateServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Test",
			Handler:    _TemplateService_Test_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "template_service.proto",
}
